/** Available food images in public/food/ — used by the image picker in ProductForm. */
const FOOD_IMAGES = [
  { url: "/food/air-fryer-tandoori-chicken.jpg", name: "Air Fryer Tandoori Chicken" },
  { url: "/food/beef-luwombo.jpg", name: "Beef Luwombo" },
  { url: "/food/box_meal.png", name: "Box Meal" },
  { url: "/food/chapati.jpg", name: "Chapati" },
  { url: "/food/cheesy-bbq-chicken-pizza.webp", name: "Cheesy BBQ Chicken Pizza" },
  { url: "/food/chicken-luwombo.jpg", name: "Chicken Luwombo" },
  { url: "/food/chips-and-chicken.jpg", name: "Chips & Chicken" },
  { url: "/food/coca-cola.jpg", name: "Coca Cola" },
  { url: "/food/crispy-oven-sausages.jpg", name: "Crispy Oven Sausages" },
  { url: "/food/crispy-samosa-pinwheels.jpg", name: "Crispy Samosa Pinwheels" },
  { url: "/food/double-burger-deal.jpg", name: "Double Burger Deal" },
  { url: "/food/fast-food-combo.jpg", name: "Fast Food Combo" },
  { url: "/food/fish-and-chips.jpg", name: "Fish & Chips" },
  { url: "/food/glass-cocacola.jpg", name: "Glass Coca Cola" },
  { url: "/food/goat-meat-and-rice.jpg", name: "Goat Meat & Rice" },
  { url: "/food/lipton-onion-soup-burger.webp", name: "Lipton Onion Soup Burger" },
  { url: "/food/low-carb-meatballs.jpg", name: "Low Carb Meatballs" },
  { url: "/food/matooke-and-beef.jpg", name: "Matooke & Beef" },
  { url: "/food/matooke-and-fish.jpg", name: "Matooke & Fish" },
  { url: "/food/matooke-with-groundnuts.jpg", name: "Matooke with Groundnuts" },
  { url: "/food/nyama-choma.jpg", name: "Nyama Choma" },
  { url: "/food/pilao-beef.jpg", name: "Pilao Beef" },
  { url: "/food/plain-chips.webp", name: "Plain Chips" },
  { url: "/food/plastic-cocacola.jpg", name: "Plastic Coca Cola" },
  { url: "/food/roasted-duck-in-wine.jpg", name: "Roasted Duck in Wine" },
  { url: "/food/roasted-goat-meat.jpg", name: "Roasted Goat Meat" },
  { url: "/food/sharing_bucket.png", name: "Sharing Bucket" },
  { url: "/food/tassot-cabrit.jpg", name: "Tassot Cabrit" },
  { url: "/food/ugandan-kikomando.jpg", name: "Ugandan Kikomando" },
  { url: "/food/ugandan-local-food-mega-combo.jpg", name: "Ugandan Local Food Mega Combo" },
  { url: "/food/ugandan-rolex.jpg", name: "Ugandan Rolex" },
];

export default FOOD_IMAGES;
