-- ═══════════════════════════════════════════════════════════════════
-- Wabz Foods — Database setup: site_settings, feedback, Row Level Security
-- ═══════════════════════════════════════════════════════════════════
-- Paste into Supabase SQL Editor (SQL > New query) and Run.
-- Idempotent: safe to run more than once.
--
-- AFTER APPLYING THIS:
--   * Anon visitors can still read the menu and place/track orders
--     (checkout + phone-based tracking run anonymously in the app).
--   * Menu / order / settings writes now require a signed-in session
--     (the "authenticated" role) or the service role.
--   * Re-run seed scripts with the SERVICE ROLE key, e.g.:
--       $env:SUPABASE_SERVICE_ROLE_KEY="..." ; node lib/seed-food-items.mjs
--     (the anon-key fallback still works while a table has RLS off).
-- ═══════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────
-- 1. site_settings — single-row restaurant settings used by the footer
--    and the admin "Settings" tab.
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.site_settings (
  id                     integer primary key default 1 check (id = 1),
  name                   text not null default 'Wabz Foods',
  phone                  text not null default '+256 700 123 456',
  address                text not null default 'Plot 15, Kampala Road, Kampala, Uganda',
  delivery_fee           text not null default '5000',
  delivery_radius        text not null default '10',
  opening_time           text not null default '08:00',
  closing_time           text not null default '22:00',
  footer_accent          text not null default '#e34234',
  footer_accent_secondary text not null default '#fbbf24',
  stat_menu_items        text not null default '150+',
  stat_orders_delivered  text not null default '12K+',
  stat_avg_delivery_time text not null default '30m',
  stat_expert_chefs      text not null default '15+',
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

-- Seed the single settings row (kept in sync with DEFAULT_SETTINGS).
insert into public.site_settings (id) values (1)
on conflict (id) do nothing;

alter table public.site_settings enable row level security;

drop policy if exists "site_settings anon select" on public.site_settings;
create policy "site_settings anon select"
  on public.site_settings for select
  to anon, authenticated
  using (true);

drop policy if exists "site_settings auth write" on public.site_settings;
create policy "site_settings auth write"
  on public.site_settings for all
  to authenticated
  using (true) with check (true);

-- ─────────────────────────────────────────────────────────────────────
-- 2. feedback — ready for the admin "Feedback" tab + a future review
--    widget. Customers may submit anonymously; only signed-in users
--    (admins) can read entries.
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.feedback (
  id         bigint generated by default as identity primary key,
  name       text,
  phone      text,
  rating     integer check (rating between 1 and 5),
  message    text not null,
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

drop policy if exists "feedback anon insert" on public.feedback;
create policy "feedback anon insert"
  on public.feedback for insert
  to anon, authenticated
  with check (true);

drop policy if exists "feedback auth select" on public.feedback;
create policy "feedback auth select"
  on public.feedback for select
  to authenticated
  using (true);

-- ─────────────────────────────────────────────────────────────────────
-- 3. Row Level Security on the existing tables.
--    Keeps every current app flow working while closing anonymous writes:
--      * menu (food_items, categories):     public read, signed-in write
--      * orders + order_items:              anon SELECT (phone tracking) +
--                                           anon INSERT (checkout),
--                                           signed-in write (admin updates)
-- ─────────────────────────────────────────────────────────────────────

do $$
begin
  if to_regclass('public.food_items') is not null then
    alter table public.food_items enable row level security;
    drop policy if exists "food_items anon select" on public.food_items;
    create policy "food_items anon select"
      on public.food_items for select
      to anon, authenticated
      using (true);
    drop policy if exists "food_items auth write" on public.food_items;
    create policy "food_items auth write"
      on public.food_items for all
      to authenticated
      using (true) with check (true);
  end if;

  if to_regclass('public.categories') is not null then
    alter table public.categories enable row level security;
    drop policy if exists "categories anon select" on public.categories;
    create policy "categories anon select"
      on public.categories for select
      to anon, authenticated
      using (true);
    drop policy if exists "categories auth write" on public.categories;
    create policy "categories auth write"
      on public.categories for all
      to authenticated
      using (true) with check (true);
  end if;

  if to_regclass('public.orders') is not null then
    alter table public.orders enable row level security;
    drop policy if exists "orders anon select" on public.orders;
    create policy "orders anon select"
      on public.orders for select
      to anon, authenticated
      using (true);
    drop policy if exists "orders anon insert" on public.orders;
    create policy "orders anon insert"
      on public.orders for insert
      to anon
      with check (true);
    drop policy if exists "orders auth write" on public.orders;
    create policy "orders auth write"
      on public.orders for all
      to authenticated
      using (true) with check (true);
  end if;

  if to_regclass('public.order_items') is not null then
    alter table public.order_items enable row level security;
    drop policy if exists "order_items anon select" on public.order_items;
    create policy "order_items anon select"
      on public.order_items for select
      to anon, authenticated
      using (true);
    drop policy if exists "order_items anon insert" on public.order_items;
    create policy "order_items anon insert"
      on public.order_items for insert
      to anon
      with check (true);
    drop policy if exists "order_items auth write" on public.order_items;
    create policy "order_items auth write"
      on public.order_items for all
      to authenticated
      using (true) with check (true);
  end if;
end $$;
